-- Find Total Customers by countries
SELECT country, COUNT(customer_id) AS total_customers  FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customer by gender
SELECT gender, COUNT(customer_id) AS total_customers  FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT category, COUNT(product_id) AS total_products  FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- Avg cost in each category
SELECT category, AVG(cost) AS avg_cost  FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Total revenue for each category
SELECT p.category, SUM(s.sales_amount) AS total_sales  FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC

-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_sales DESC

-- What is the distribution of sold items across countries
SELECT
c.country,
SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

